Validate isolated option
ansible/ansible-compat pull request #335
Opened 2023-10-03 12:21 UTC by shatakshiiii

Closes: https://github.com/ansible/ansible-compat/issues/324

2023-10-04 11:59 UTC, ssbarnea requested changes
We do not want to lower the code coverage, removing of the test is a very bad idea and coverage was there to remind us not to make this mistake.

The correct solution for this is to modify the tests to check for the new behavior instead of removing them.

2023-10-04 15:38 UTC, cidrblock commented
Removing the conditional allows the number of tests to be dropped. As time permits, please add a test or 2 in a seperate PR to return coverage to it's previous value or higher.

2023-10-04 15:38 UTC, cidrblock approved these changes

2023-10-05 05:35 UTC, shatakshiiii commented
@ssbarnea  Also I realized that the changes in this PR is not responsible for lowering the code coverage, we could even see codecov failing in other open PRs. And dropping some unnecessary tests is suppose to happen as per these code changes.

2023-10-06 13:09 UTC, merged