Updated Dependency : types-pkg-resources to types-setuptools
ansible/ansible-compat pull request #398
Opened 2024-08-07 16:46 UTC by tanwigeetika1618

- Update pre-commit hook to replace yanked types-pkg-resources with types-setuptools

- All versions of types-pkg_resources have been marked as yanked. Updated the dependency to types-setuptools as specified on PyPI (https://pypi.org/project/types-pkg-resources/). This ensures compatibility and resolves the package installation error.  And it solves the issue during the "[pre-commit.ci](http://pre-commit.ci/) - pr — error during build" check (https://github.com/ansible/ansible-compat/pull/397), specifically related to the types-pkg_resources package.

2024-08-09 08:05 UTC, audgirka requested changes

2024-08-09 08:05 UTC, audgirka commented on src/ansible_compat/constants.py
> +Namespace: https://ansible.readthedocs.io/projects/galaxy-ng/en/latest/usage_guide/collections/#namespaces
@tanwigeetika1618 changes from this file are in another PR
Since this is a pre-commit changes related PR, please remove this change from here

2024-08-12 12:13 UTC, shatakshiiii approved these changes

2024-08-12 14:06 UTC, audgirka approved these changes

2024-08-12 14:06 UTC, merged